GET localhost:8080/auth/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI1MWRiMDM2NWE3YzA0YzFkODE4NDU4ZWJhMGFjNjdjYiIsImV4cCI6MTU5NjE5NTE4OH0.1wbvn4Cj_siwz9kLaQX-RsnrF0nF4wmIx9gj50EuFn3WYMl0IIF9RhO2IYKg31R0yzSCXIOfdf8RBvVZ9uVSuQ

###
